# Generated by Django 5.0.1 on 2024-01-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samasya', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
