# Generated by Django 5.0.1 on 2024-01-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samasya', '0003_remove_customer_name_customer_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fullname',
        ),
    ]
