# Generated by Django 5.0.1 on 2024-01-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samasya', '0005_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='province',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ward',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('environment', 'Environment'), ('others', 'Others')], max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='level',
            field=models.CharField(choices=[('national', 'National'), ('municipality', 'Municipality'), ('ward', 'Ward')], max_length=250),
        ),
    ]
