# Generated by Django 5.0.1 on 2024-01-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samasya', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anonymous',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
